name: Run integration tests

on:
  schedule:
    - cron: '30 5 * * *'

jobs:
  php-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          tools: composer:v2

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache composer dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: php-8.1-composer-prefer-stable-${{ hashFiles('**/composer.json') }}
          restore-keys: php-8.1-composer-prefer-stable-

      - name: Install dependencies
        env:
          MELVIN_USERNAME: ${{ secrets.MELVIN_USERNAME }}
          MELVIN_PASSWORD: ${{ secrets.MELVIN_PASSWORD }}
        run: composer update --prefer-stable --prefer-dist --no-interaction

      - name: Execute tests
        run: vendor/bin/phpunit --testsuite=integration
